version: '3.2'

services:
  cypress:
    image: cypress/included:5.4.0
    container_name: cypress
    working_dir: /e2e
    volumes:
        - ./:/e2e
    command: "--record --key 89e71fe7-37f8-47f2-a1d5-8866297ce743 --spec='cypress/integration/affise/*.js'"